spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix:  .html
    mode: LEGACYHTML5
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-idle: 10 #最大空闲数目
        max-wait: 100000
        min-idle: 4 #最小空闲数目
    password: root
    database: 0
    timeout: 1000
  datasource:
    url: jdbc:mysql://localhost:3306/oa?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    password: 199712
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root

mybatis:
  type-aliases-package: com.fanfan.pojo
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 500
    default-statement-timeout: 80
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl